services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: altamimi
      POSTGRES_USER: altamimi
      POSTGRES_PASSWORD: altamimi
    ports:
      - "5432:5432"
    volumes:
      - altamimi_pg:/var/lib/postgresql/data

volumes:
  altamimi_pg:
